### ISSUE TITLE
Disable extracting system packages?

### ISSUE THREAD

**Issue by nyanpasu64** [SublimeText/ExtractSublimePackage#2]
I'm debugging a problem where Sublime always detects tabs, to figure out which plugin is responsible. So I'm writing a Python script to do a binary search among all installed plugins, and this script is cluttered by extracted system packages.

I already trashed my package directory trying to debug this issue, and don't exactly have the time to figure out whatever your `multi_importer` is doing.

So is it possible to disable extracting system packages?

**Comment by FichteFoll** [comment]
Being able to extract system packages as well as installed packages seems to me like an intended feature, so no, I don't think removing that functionality makes sense.
